# fly.toml app configuration file generated for sac-bot on 2025-12-31T15:57:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sac-bot"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "10GB"
  auto_extend_size_threshold = 80

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
